name: 'License-Generator'
author: 'yi_Xu'
description: 'Use default template to generate license.'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  path:
    description: 'Set up the path of license.'
    required: false
    default: LICENSE
  type:
    description: 'Set up the type of license.'
    required: false
    default: MIT
  year:
    description: 'Set up the year when to since from of license.'
    required: false
    default: none
  author:
    description: 'Set up the author of license.'
    required: false
    default: ${{ github.actor }}
  work:
    description: 'Set up the work name of license.'
    required: false
    default: ${{ github.repository }}

runs:
  using: 'node12'
  main: 'dist/index.js'
