name: MIT

on:
  schedule:
    - cron: '1 1 * * *'

jobs:
  run:
    name: Generate MIT License
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.3

      - name: Generate License
        uses: ./
        with:
          path: LICENSE
          type: MIT
          year: 2019
          author: yi_Xu

      - name: Show License
        run: |
          cat LICENSE
